export const ENDPOINTS = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    me: '/auth/me',
  },
  dashboard: '/dashboard',
  notifications: '/notifications',
  orders: {
    list: '/orders',
    create: '/orders',
    details: (id: string) => `/orders/${id}`,
    update: (id: string) => `/orders/${id}`,
    delete: (id: string) => `/orders/${id}`,
  },
  customers: {
    list: '/customers',
    create: '/customers',
    details: (id: string) => `/customers/${id}`,
    update: (id: string) => `/customers/${id}`,
    delete: (id: string) => `/customers/${id}`,
    prescriptions: (id: string) => `/customers/${id}/prescriptions`,
    orders: (id: string) => `/customers/${id}/orders`,
  },
  prescriptions: {
    create: (customerId: string) => `/customers/${customerId}/prescriptions`,
    details: (id: string) => `/prescriptions/${id}`,
    update: (id: string) => `/prescriptions/${id}`,
    delete: (id: string) => `/prescriptions/${id}`,
  },
  appointments: {
    list: '/appointments',
    create: '/appointments',
    walkIn: '/appointments/walk-in',
    details: (id: string) => `/appointments/${id}`,
    update: (id: string) => `/appointments/${id}`,
    delete: (id: string) => `/appointments/${id}`,
    forCustomer: (customerId: string) => `/customers/${customerId}/appointments`,
  },
  ledger: {
    list: '/ledger',
    details: (customerId: string) => `/ledger/${customerId}`,
    addPayment: '/ledger/payment',
    addAdjustment: '/ledger/adjustment',
    updateTransaction: (transactionId: string) => `/ledger/${transactionId}`,
    deleteTransaction: (transactionId: string) => `/ledger/${transactionId}`,
    report: '/ledger/report',
  },
  calendar: {
    events: '/calendar/events',
    summary: '/calendar/summary',
    createReminder: '/calendar/reminders',
    deleteReminder: (id: string) => `/calendar/reminders/${id}`,
    createStaffSchedule: '/calendar/staff-schedule',
    deleteStaffSchedule: (id: string) => `/calendar/staff-schedule/${id}`,
  },
  visits: {
    create: '/visits',
    list: (customerId: string) => `/visits/customer/${customerId}`,
    delete: (id: string) => `/visits/${id}`,
  },
} as const;
